server:
  port: 8083

spring:
  application:
    name: api-gateway

AUTH_SERVICE_URL: 'http://localhost:8084'
FILE_SERVICE_URL: 'http://localhost:8081'
NOTIFICATION_SERVICE_URL: 'http://localhost:8082'

keycloak:
  url: ${KEYCLOAK_URL:http://localhost:8080}
  realm: microservices-realm
  jwks-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8080/realms/microservices-realm/protocol/openid-connect/certs}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: INFO
